// students.js

export const students = [
  // 🔹 Male Students - 12-Nickel
  { studentid: "M001", name: "BACUS, JEAN MARK S.", section: "12-Nickel" },
  { studentid: "M002", name: "BALTAZAR, RENZLEY B.", section: "12-Nickel" },
  { studentid: "M003", name: "BALTAZAR, SUN-JAY DC.", section: "12-Nickel" },
  { studentid: "M004", name: "BARBOZA, PETER JULIAN EYMARD F.", section: "12-Nickel" },
  { studentid: "M005", name: "DELA CRUZ, JUSTIN", section: "12-Nickel" },
  { studentid: "M006", name: "GARCIA, WHACKY AUSTINE", section: "12-Nickel" },
  { studentid: "M007", name: "GOMEZ, JEROME G.", section: "12-Nickel" },
  { studentid: "M008", name: "GONZALES, ALLEN S.", section: "12-Nickel" },
  { studentid: "M009", name: "HERNANDEZ, REIN JARRED P.", section: "12-Nickel" },
  { studentid: "M010", name: "LIWAG, NEITHAN JHARRED B.", section: "12-Nickel" },
  { studentid: "M011", name: "LONGAKIT II, DANILO O.", section: "12-Nickel" },
  { studentid: "M012", name: "MALLARE, MATT JIMWELLE S.", section: "12-Nickel" },
  { studentid: "M013", name: "MANUZON, RAINIER AARON C.", section: "12-Nickel" },
  { studentid: "M014", name: "MENDEZ, AJ ANDREI B.", section: "12-Nickel" },
  { studentid: "M015", name: "PABLO, RAVEN M.", section: "12-Nickel" },
  { studentid: "M016", name: "PACHECO, ADRIAN B.", section: "12-Nickel" },
  { studentid: "M017", name: "PELAYO, AJ CHRISTOPHER M.", section: "12-Nickel" },
  { studentid: "M018", name: "PELAYO, JAYVEE N.", section: "12-Nickel" },
  { studentid: "M019", name: "RAMOS, PRINZ SEDRIEL L.", section: "12-Nickel" },
  { studentid: "M020", name: "RIVERA, RYAN JAMES N.", section: "12-Nickel" },
  { studentid: "M021", name: "SALVADOR, LHANZE S.", section: "12-Nickel" },
  { studentid: "M022", name: "SANTOS, MARK ARVIN D.", section: "12-Nickel" },
  { studentid: "M023", name: "SANTOS, MIGUEL JHON G.", section: "12-Nickel" },
  { studentid: "M024", name: "SILVERIO, JOSEF O.", section: "12-Nickel" },
  { studentid: "M025", name: "SUBA, ACE VERGEL P.", section: "12-Nickel" },
  { studentid: "M026", name: "VILLAS, JHAMIL S.", section: "12-Nickel" },
  { studentid: "M027", name: "YAMSON, ARDYNL L.", section: "12-Nickel" },
  { studentid: "M028", name: "CAJANDING, JASMER IVOH D.", section: "12-Nickel" },

  // 🔹 Female Students - 12-Nickel
  { studentid: "F001", name: "AYUBAN, KRISTEL ANNE B.", section: "12-Nickel" },
  { studentid: "F002", name: "BELTRAN, AYESHA MAE T.", section: "12-Nickel" },
  { studentid: "F003", name: "CABUSAS, ANGELICA P.", section: "12-Nickel" },
  { studentid: "F004", name: "LACSINA, KINNILY TIFFANY", section: "12-Nickel" },
  { studentid: "F005", name: "LINSANGAN, JANE CRISTINE DC.", section: "12-Nickel" },
  { studentid: "F006", name: "MANANGHAYA, DENCEL B.", section: "12-Nickel" },
  { studentid: "F007", name: "MANUZON, MARIDEL DP.", section: "12-Nickel" },
  { studentid: "F008", name: "NIWA, ARISA M.", section: "12-Nickel" },
  { studentid: "F009", name: "PAYOFELIN, PEARLYN CLEOFE D.", section: "12-Nickel" },
  { studentid: "F010", name: "RAMOS, PRINCES ZERYN L.", section: "12-Nickel" },
  { studentid: "F011", name: "SANTOS, ASHLY NICHOLE D.", section: "12-Nickel" },
  { studentid: "F012", name: "VILLANUEVA, VERONECA A.", section: "12-Nickel" }
];